name: Run Parallel Tests And Generate Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *'  # Schedule to run at 3 AM EST daily

permissions:
  contents: write
  actions: write

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            browser: headless-firefox
          - os: windows-latest
            browser: headless-chrome
          - os: macos-latest
            browser: headless-edge
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Prepare configuration.properties
        run: |
          echo "browser=${{ matrix.browser }}" > configuration.properties

      - name: Ensure Allure results directory
        run: mkdir -p allure-results

      - name: Run Parallel Tests
        run: mvn -B clean test -Dbrowser=${{ matrix.browser }}

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.os }}-${{ matrix.browser }}
          path: allure-results

  generate-report:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Allure results from Firefox
        uses: actions/download-artifact@v4
        with:
          name: allure-results-ubuntu-latest-headless-firefox
          path: allure-results-firefox

      - name: Download Allure results from Chrome
        uses: actions/download-artifact@v4
        with:
          name: allure-results-windows-latest-headless-chrome
          path: allure-results-chrome

      - name: Download Allure results from Edge
        uses: actions/download-artifact@v4
        with:
          name: allure-results-macos-latest-headless-edge
          path: allure-results-edge

      - name: Merge Allure results
        run: |
          mkdir -p merged-results
          cp -r allure-results-firefox/* merged-results/
          cp -r allure-results-chrome/* merged-results/
          cp -r allure-results-edge/* merged-results/

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: merged-results
          allure_report: allure-report

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report